import { Project, UserProfile } from "../types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    ownerId: 'u1',
    ownerName: 'Ahmed Bencherif',
    ownerPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
    title: 'E-commerce Website for Algerian Craft Shop',
    description: 'We need a full-featured e-commerce website to sell traditional Algerian crafts. Must include payment integration (mock), inventory management, and a clean responsive design.',
    budget: 45000,
    deliveryTime: '30 days',
    category: 'Programming & Tech',
    attachments: [],
    status: 'open',
    offerCount: 12,
    createdAt: new Date(),
  },
  {
    id: '2',
    ownerId: 'u2',
    ownerName: 'Sara Djazairi',
    ownerPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara',
    title: 'Logo Design for New Startup in Algiers',
    description: 'Looking for a minimalist and modern logo design for a tech startup. The brand represents innovation and local heritage.',
    budget: 15000,
    deliveryTime: '7 days',
    category: 'Graphics & Design',
    attachments: [],
    status: 'open',
    offerCount: 24,
    createdAt: new Date(),
  },
  {
    id: '3',
    ownerId: 'u3',
    ownerName: 'Yassine Karim',
    ownerPhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Yassine',
    title: 'Mobile App for Food Delivery in Oran',
    description: 'Developing a food delivery application for the city of Oran. Need a React Native developer to help with the customer-facing app.',
    budget: 80000,
    deliveryTime: '60 days',
    category: 'Mobile App Dev',
    attachments: [],
    status: 'open',
    offerCount: 8,
    createdAt: new Date(),
  },
];

export const MOCK_FREELANCERS: UserProfile[] = [
  {
    uid: 'f1',
    name: 'Mohamed Amine',
    email: 'mohamed@example.dz',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mohamed',
    bio: 'Full-stack developer with 5+ years of experience in React, Next.js, and Firebase. I build high-performance web applications.',
    skills: ['React', 'Next.js', 'Firebase', 'TypeScript', 'Node.js'],
    portfolio: [],
    rating: 4.9,
    reviewCount: 42,
    completedProjects: 56,
    trustScore: 98,
    isVerified: true,
    phoneVerified: true,
    emailVerified: true,
    createdAt: new Date(),
  },
  {
    uid: 'f2',
    name: 'Lina Belkacem',
    email: 'lina@example.dz',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lina',
    bio: 'Creative UI/UX designer and Illustrator. Passionate about creating beautiful and functional digital experiences.',
    skills: ['Figma', 'Adobe XD', 'Illustrator', 'UI Design', 'UX Research'],
    portfolio: [],
    rating: 5.0,
    reviewCount: 28,
    completedProjects: 31,
    trustScore: 95,
    isVerified: true,
    phoneVerified: true,
    emailVerified: true,
    createdAt: new Date(),
  },
  {
    uid: 'f3',
    name: 'Ryad Mansouri',
    email: 'ryad@example.dz',
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ryad',
    bio: 'Digital marketing expert helping Algerian businesses grow online through SEO and social media strategy.',
    skills: ['SEO', 'SEM', 'Social Media', 'Content Strategy', 'Analytics'],
    portfolio: [],
    rating: 4.7,
    reviewCount: 19,
    completedProjects: 24,
    trustScore: 88,
    isVerified: false,
    phoneVerified: true,
    emailVerified: true,
    createdAt: new Date(),
  },
];
